"""create_initial_issue_detection_schema

Revision ID: cc291a0f3582
Revises: 
Create Date: 2026-06-07 00:39:47.020169
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cc291a0f3582'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('department_scope', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('departments',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('service_level_hours', sa.Integer(), nullable=False),
    sa.Column('risk_weight', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('review_sources',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_verified_channel', sa.Boolean(), nullable=False),
    sa.Column('connector_key', sa.String(length=120), nullable=True),
    sa.Column('sample_import_path', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('detected_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('reputation_risk_score', sa.Integer(), nullable=False),
    sa.Column('recurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignee_name', sa.String(length=120), nullable=True),
    sa.Column('cluster_key', sa.String(length=64), nullable=False),
    sa.Column('cluster_centroid', sa.JSON(), nullable=False),
    sa.Column('embedding_model_name', sa.String(length=120), nullable=False),
    sa.Column('title_generated_by', sa.String(length=32), nullable=False),
    sa.Column('title_generation_model', sa.String(length=120), nullable=True),
    sa.Column('title_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_key')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connector_key', sa.String(length=120), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_duplicate_flagged', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_code'], ['review_sources.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['detected_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('external_review_id', sa.String(length=120), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_code'], ['review_sources.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'external_review_id', name='uq_raw_reviews_source_external_id')
    )
    op.create_table('normalized_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_review_id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('external_review_id', sa.String(length=120), nullable=False),
    sa.Column('reviewer_name', sa.String(length=120), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_content_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_review_id', sa.Integer(), nullable=True),
    sa.Column('normalized_payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_review_id'], ['normalized_reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_review_id'], ['raw_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_code'], ['review_sources.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_review_id'),
    sa.UniqueConstraint('source_code', 'external_review_id', name='uq_normalized_reviews_source_external_id')
    )
    op.create_table('issue_review_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_triggering_evidence', sa.Boolean(), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['detected_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['normalized_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'review_id', name='uq_issue_review_link')
    )
    op.create_table('review_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=32), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_confidence', sa.Float(), nullable=False),
    sa.Column('department_code', sa.String(length=64), nullable=False),
    sa.Column('department_confidence', sa.Float(), nullable=False),
    sa.Column('department_model_name', sa.String(length=120), nullable=False),
    sa.Column('reputation_risk_score', sa.Integer(), nullable=False),
    sa.Column('reputation_risk_label', sa.String(length=32), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model_name', sa.String(length=120), nullable=True),
    sa.Column('embedding_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_version', sa.String(length=64), nullable=False),
    sa.Column('explanation_factors', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['normalized_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_analyses')
    op.drop_table('issue_review_links')
    op.drop_table('normalized_reviews')
    op.drop_table('raw_reviews')
    op.drop_table('issue_events')
    op.drop_table('ingestion_runs')
    op.drop_table('detected_issues')
    op.drop_table('review_sources')
    op.drop_table('departments')
    op.drop_table('demo_roles')
    # ### end Alembic commands ###
