SEED_REVIEWS = [
    {
        "external_review_id": "seed-kg-001",
        "source_code": "google_business_profile",
        "reviewer_name": "Ayesha F.",
        "review_date": "2026-06-12T10:30:00+00:00",
        "rating": 2.0,
        "language": "en",
        "title": "Room was not ready",
        "body": "Check-in took too long and the room was still being cleaned when we arrived.",
    },
    {
        "external_review_id": "seed-kg-002",
        "source_code": "google_business_profile",
        "reviewer_name": "Michael R.",
        "review_date": "2026-06-13T14:15:00+00:00",
        "rating": 3.0,
        "language": "en",
        "title": "Breakfast queue was slow",
        "body": "The breakfast spread was good, but queues were long and staff seemed stretched.",
    },
    {
        "external_review_id": "seed-kg-003",
        "source_code": "google_business_profile",
        "reviewer_name": "Nadeesha P.",
        "review_date": "2026-06-14T08:00:00+00:00",
        "rating": 5.0,
        "language": "en",
        "title": "Excellent service recovery",
        "body": "The guest relations team followed up quickly and made our anniversary stay memorable.",
    },
    {
        "external_review_id": "seed-kg-004",
        "source_code": "google_business_profile",
        "reviewer_name": "Priyan S.",
        "review_date": "2026-06-15T19:45:00+00:00",
        "rating": 2.0,
        "language": "en",
        "title": "Air conditioning problem",
        "body": "The air conditioning did not cool the room properly and maintenance took hours to respond.",
    },
    {
        "external_review_id": "seed-kg-005",
        "source_code": "google_business_profile",
        "reviewer_name": "Sara K.",
        "review_date": "2026-06-16T16:20:00+00:00",
        "rating": 2.0,
        "language": "en",
        "title": "Bathroom cleanliness",
        "body": "The bathroom floor and sink were not cleaned well before we checked in.",
    },
    {
        "external_review_id": "seed-kg-006",
        "source_code": "google_business_profile",
        "reviewer_name": "Daniel W.",
        "review_date": "2026-06-17T21:10:00+00:00",
        "rating": 3.0,
        "language": "en",
        "title": "Event noise carried into room",
        "body": "Music from an event was audible late at night and made it difficult to sleep.",
    },
    {
        "external_review_id": "seed-kg-007",
        "source_code": "google_business_profile",
        "reviewer_name": "Kamal J.",
        "review_date": "2026-06-18T22:00:00+00:00",
        "rating": 1.0,
        "language": "en",
        "title": "AC not cooling at all",
        "body": "The air conditioner was broken and the room was unbearably hot all night. We could not sleep.",
    },
    {
        "external_review_id": "seed-kg-008",
        "source_code": "google_business_profile",
        "reviewer_name": "Lihini G.",
        "review_date": "2026-06-19T09:30:00+00:00",
        "rating": 2.0,
        "language": "en",
        "title": "Dirty bathroom with mold",
        "body": "The bathroom was not properly cleaned, and there was mold near the shower.",
    },
]
