REVIEW_SOURCES = [
    {
        "code": "google_business_profile",
        "name": "Google Business Profile",
        "description": "Official-shaped verified review connector for Google hotel reviews.",
        "default_enabled": True,
        "is_verified_channel": True,
        "connector_key": "google_business_profile",
        "sample_import_path": None,
        "source_metadata": {
            "kpi_scope": "verified_reviews",
            "live_credentials_required": False,
            "verified_review_source": True,
            "connector_mode": "mock_official_shaped",
            "provider_payload_shape": "businessprofile.googleapis.com account location review",
        },
    },
    {
        "code": "booking_com",
        "name": "Booking.com",
        "description": "Official-shaped verified review connector for Booking.com guest reviews.",
        "default_enabled": True,
        "is_verified_channel": True,
        "connector_key": "booking_com",
        "sample_import_path": None,
        "source_metadata": {
            "kpi_scope": "verified_reviews",
            "live_credentials_required": False,
            "verified_review_source": True,
            "connector_mode": "mock_official_shaped",
            "provider_payload_shape": "connectivity guest review with reservation and score breakdown",
        },
    },
    {
        "code": "tripadvisor",
        "name": "Tripadvisor",
        "description": "Official-shaped verified review connector for Tripadvisor guest reviews.",
        "default_enabled": True,
        "is_verified_channel": True,
        "connector_key": "tripadvisor",
        "sample_import_path": None,
        "source_metadata": {
            "kpi_scope": "verified_reviews",
            "live_credentials_required": False,
            "verified_review_source": True,
            "connector_mode": "mock_official_shaped",
            "provider_payload_shape": "content API location review with subratings",
        },
    },
]

DEPARTMENTS = [
    {
        "code": "front_office",
        "name": "Front Office",
        "description": "Reception, check-in, check-out, booking changes, and guest arrival experience.",
        "service_level_hours": 24,
        "risk_weight": 12,
        "sort_order": 10,
    },
    {
        "code": "housekeeping",
        "name": "Housekeeping",
        "description": "Room cleanliness, linen, amenities replenishment, and floor-level service recovery.",
        "service_level_hours": 24,
        "risk_weight": 14,
        "sort_order": 20,
    },
    {
        "code": "food_beverage",
        "name": "Food and Beverage",
        "description": "Restaurants, bars, in-room dining, breakfast, banquets, and event catering.",
        "service_level_hours": 24,
        "risk_weight": 12,
        "sort_order": 30,
    },
    {
        "code": "engineering",
        "name": "Engineering",
        "description": "Room condition, air conditioning, plumbing, lifts, power, and facility defects.",
        "service_level_hours": 48,
        "risk_weight": 16,
        "sort_order": 40,
    },
    {
        "code": "guest_relations",
        "name": "Guest Relations",
        "description": "Service recovery, follow-up, escalations, and cross-department guest experience trends.",
        "service_level_hours": 24,
        "risk_weight": 12,
        "sort_order": 50,
    },
    {
        "code": "management",
        "name": "Management",
        "description": "Pricing, value perception, strategy, and cross-department management coordination.",
        "service_level_hours": 72,
        "risk_weight": 18,
        "sort_order": 60,
    },
]

DEMO_ROLES = [
    {
        "code": "admin",
        "name": "Prototype Admin",
        "description": "Demo role with full configuration and operational access.",
        "permissions": ["config:read", "config:write", "reviews:read", "issues:manage", "analytics:read"],
        "department_scope": ["*"],
    },
    {
        "code": "operations_manager",
        "name": "Operations Manager",
        "description": "Hotel operations role that can monitor all departments and manage issues.",
        "permissions": ["config:read", "reviews:read", "issues:manage", "analytics:read"],
        "department_scope": ["front_office", "housekeeping", "food_beverage", "engineering", "guest_relations", "management"],
    },
    {
        "code": "department_head",
        "name": "Department Head",
        "description": "Department owner role for triaging and resolving assigned issues.",
        "permissions": ["config:read", "reviews:read", "issues:manage"],
        "department_scope": ["assigned_department"],
    },
    {
        "code": "analyst",
        "name": "Review Analyst",
        "description": "Demo analyst role for reviewing insights and source configuration.",
        "permissions": ["config:read", "reviews:read", "analytics:read"],
        "department_scope": [],
    },
]
