SEED_REVIEWS = [
    {
        "external_review_id": "seed-kg-001",
        "source_code": "kingsbury_seed_dataset",
        "source_name": "Kingsbury Demo Seed Dataset",
        "reviewer_name": "Ayesha F.",
        "review_date": "2026-06-12T10:30:00+00:00",
        "rating": 2.0,
        "language": "en",
        "title": "Room was not ready",
        "body": "Check-in took too long and the room was still being cleaned when we arrived.",
        "sentiment_label": "negative",
        "sentiment_score": -0.62,
        "issue_category_code": "booking_checkin",
        "severity": "high",
        "department_code": "front_office",
    },
    {
        "external_review_id": "seed-kg-002",
        "source_code": "kingsbury_seed_dataset",
        "source_name": "Kingsbury Demo Seed Dataset",
        "reviewer_name": "Michael R.",
        "review_date": "2026-06-13T14:15:00+00:00",
        "rating": 3.0,
        "language": "en",
        "title": "Breakfast queue was slow",
        "body": "The breakfast spread was good, but queues were long and staff seemed stretched.",
        "sentiment_label": "mixed",
        "sentiment_score": -0.18,
        "issue_category_code": "service_delay",
        "severity": "medium",
        "department_code": "guest_relations",
    },
    {
        "external_review_id": "seed-kg-003",
        "source_code": "kingsbury_seed_dataset",
        "source_name": "Kingsbury Demo Seed Dataset",
        "reviewer_name": "Nadeesha P.",
        "review_date": "2026-06-14T08:00:00+00:00",
        "rating": 5.0,
        "language": "en",
        "title": "Excellent service recovery",
        "body": "The guest relations team followed up quickly and made our anniversary stay memorable.",
        "sentiment_label": "positive",
        "sentiment_score": 0.84,
        "issue_category_code": "positive_general",
        "severity": "low",
        "department_code": "guest_relations",
    },
    {
        "external_review_id": "seed-kg-004",
        "source_code": "kingsbury_seed_dataset",
        "source_name": "Kingsbury Demo Seed Dataset",
        "reviewer_name": "Priyan S.",
        "review_date": "2026-06-15T19:45:00+00:00",
        "rating": 2.0,
        "language": "en",
        "title": "Air conditioning problem",
        "body": "The air conditioning did not cool the room properly and maintenance took hours to respond.",
        "sentiment_label": "negative",
        "sentiment_score": -0.71,
        "issue_category_code": "room_condition",
        "severity": "high",
        "department_code": "engineering",
    },
    {
        "external_review_id": "seed-kg-005",
        "source_code": "kingsbury_seed_dataset",
        "source_name": "Kingsbury Demo Seed Dataset",
        "reviewer_name": "Sara K.",
        "review_date": "2026-06-16T16:20:00+00:00",
        "rating": 2.0,
        "language": "en",
        "title": "Bathroom cleanliness",
        "body": "The bathroom floor and sink were not cleaned well before we checked in.",
        "sentiment_label": "negative",
        "sentiment_score": -0.77,
        "issue_category_code": "cleanliness",
        "severity": "high",
        "department_code": "housekeeping",
    },
    {
        "external_review_id": "seed-kg-006",
        "source_code": "kingsbury_seed_dataset",
        "source_name": "Kingsbury Demo Seed Dataset",
        "reviewer_name": "Daniel W.",
        "review_date": "2026-06-17T21:10:00+00:00",
        "rating": 3.0,
        "language": "en",
        "title": "Event noise carried into room",
        "body": "Music from an event was audible late at night and made it difficult to sleep.",
        "sentiment_label": "negative",
        "sentiment_score": -0.48,
        "issue_category_code": "noise_events",
        "severity": "medium",
        "department_code": "guest_relations",
    },
]
